### ISSUE TITLE
1.15-1.19 Project Schedule

### ISSUE THREAD

**Issue by IRONICBo** [goplus/community#38]
# Description

We need to set up the tasks and scheduling for each Task, each task need to be associated with one or multi PRs.

# Peer Review

- @nnnnn319 -> @Baihhh
- @xhyqaq -> @Baihhh
- @wu-jj -> @xhyqaq
- @IRONICBo  -> @xhyqaq
- @Baihhh -> @IRONICBo 
- 林杰 -> @IRONICBo 
- @Kasey0727-> @nnnnn319

# Task

1. **Account & User Module** - @wu-jj @xhyqaq

- [x] Implement account sdk in goplus community.
- [x] Implement uuid storage.
- [x] Implement article share.

3. **Article Module** - @Baihhh

- [x] Implement article creation, editing, and deletion functionality.
- [x] Article list view functionality.
- [x] Article details view functionality.
- [x] Support article translation with `translation` module. @IRONICBo 

4. **Markdown Support** - @nnnnn319
- [x] Article editor supports Markdown syntax with cherry-markdown.
- [x] Save markdown preview functionality, save to QiNiu Object Storage or local storage. @Baihhh @xhyqaq
- [x] Support goplus highlight.
- [ ] Support Video markdown tag. @IRONICBo @xhyqaq

5. **Translation Functionality** - @IRONICBo
- [x] Implement translation of markdown articles.
- [x] Implement batch translation in long text translation.
- [ ] Support video to text.
- [ ] Support text to audio.

6. **Media Module** - @xhyqaq
- [x] Users can upload and delete media files.
- [x] Media file display functionality.
- [x] Media file download functionality.

7. **User Interface** - @Kasey0727
- [x] Design and implement user interface in yap html.
- [x] Design and implement article interface in yap html.
- [x] Design and implement article list(home) interface in yap html.

Everyone is expected to complete their part by the end of this week, and submit their code and test reports. If you encounter any issues or need help during the development process, please raise it in the issue promptly.

**Comment by IRONICBo** [comment]
- Implement translation of markdown articles PR. https://github.com/goplus/community/pull/32

**Comment by IRONICBo** [comment]
- Implement translation process for video PR. https://github.com/goplus/community/pull/43

**Comment by IRONICBo** [comment]
- Add yap home page PR. https://github.com/goplus/community/pull/48
